-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
USE HOLYBIRD_DOAN2
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE DangKy 
	-- Add the parameters for the stored procedure here
	@MaDoan VarChar(4),
	@TenDangNhap VarChar(15),
	@MatKhau VarChar(15)
AS
BEGIN
	INSERT INTO dbo.TAIKHOAN VALUES (@MaDoan,@TenDangNhap,@MatKhau,0)
END
GO
EXEC DangKy '001','TAITAN','1234'

GO
DROP PROCEDURE DATPHONG3
GO
CREATE PROCEDURE DATPHONG3 
	@MaGD VARCHAR(4),
	@MaDoan VARCHAR(4),
	@Hang VARCHAR(45),
	@Tang INT,
	@HinhThuc VARCHAR(45),
	@SoPhong INT,
	@BatDau DATETIME,
	@KetThuc DATETIME
	
AS
BEGIN
	DECLARE listPhong CURSOR FOR SELECT P.MaPhong FROM PHONG P,CHITIETPHONG CTP WHERE P.MaPhong=CTP.MaPhong AND @Hang = CTP.Hang AND @HinhThuc = CTP.HinhThuc AND @Tang = CTP.Tang AND CTP.TinhTrang=0
	OPEN listPhong
	DECLARE @MaPhong VARCHAR(3)
	DECLARE @DEM INT
	SET @DEM = 0
	INSERT INTO GIAODICH VALUES (@MaGD,@MaDoan,@SoPhong,@BatDau,@KetThuc)
	FETCH NEXT FROM listPhong INTO @MaPhong
		WHILE @@FETCH_STATUS =0 
		BEGIN
			SET @DEM = @DEM + 1 
			IF @DEM <=@SoPhong
			BEGIN
				DECLARE @TenPhong VARCHAR(45)
				SELECT @TenPhong=PHONG.TenPhong FROM PHONG
					WHERE PHONG.MaPhong = @MaPhong 

				PRINT N'Phòng: '+@TenPhong +' STT  :' +CAST(@DEM AS VARCHAR)
				PRINT '-------------------------------------'
				


			END
			FETCH NEXT FROM listPhong INTO @maPhong
		END
	CLOSE listPhong
	DEALLOCATE listPhong
END
GO
--exec datphong
EXEC DATPHONG3 '003','001','Phong hang sang',1,'2 nguoi/phong',2,'2007-05-08','2007-05-09'

GO
DROP PROCEDURE NHAPGDTHANHVIENDOAN
GO
-- KHI DA THUC HIEN XONG PROCEDURE DATCHO O TREN DO TRUONG PHONG LAM, MAN HINH CONSOLE HOAC MAN HINH WINFORM HIEN RA TEN PHONG VA MA PHONG
--NGUOI TRONG DOAN MUON DANG KY SE THUC HIEN CLICK VAO PHONG DO, LAY DUOC MA PHONG, DUA VAO FUNCTION
--DANG KY CHO TUNG NGUOI NAO MUON VAO PHONG NAO.
-- LUU Y DE TIM MA GIAO DICH PHAI UNG VOI TUNG MA DOAN VA NGAY GIO MA TRUONG DOAN DANG KY
CREATE PROCEDURE NHAPGDTHANHVIENDOAN
(@MaDoan VARCHAR(45), @HoTen VARCHAR(45),@CMND VARCHAR(45),@TenPhong VARCHAR(45),@MaPhong VARCHAR(3),@BatDau DATETIME)

AS

BEGIN

DECLARE @KIEMTRA VARCHAR(50)
DECLARE @CHECK INT
DECLARE @KIEMTRATEN VARCHAR(45)
SELECT @KIEMTRATEN = HoTen FROM THANHVIENDOAN WHERE @CMND=CMND AND @HoTen = HoTen AND @MaDoan = Doan
DECLARE @MaGD VARCHAR(4)
		SELECT @MaGD =MaGD FROM GIAODICH WHERE @MaDoan=MaDoan AND @BatDau = BatDau
IF((@KIEMTRATEN IS NOT NULL) OR LEN(@KIEMTRATEN)>0 )
		IF((@MaGD IS NOT NULL) OR LEN(@MaGD)>0)
			SET @CHECK = 1
		ELSE
			SET @CHECK = 0
ELSE
	SET @CHECK  = 0
--KIEM TRA XEM THONG TIN KHACH HANG CO DUNG VOI CO SO DU LIEU K, TEN, CMND, MaDoan, TenPhong Hop Le
--NEU HOP LE, BIEN KIEM TRA = THANHCONG VA CHECK =1
--NEU CHECK = 1 thi tien hanh nap du lieu vao trong bang ChiTietGiaodich
IF(@CHECK =1)
BEGIN
		DECLARE @MaKH VARCHAR(4)
		SELECT @MaKH = MaKH FROM THANHVIENDOAN WHERE @HoTen=HoTen AND @CMND=CMND AND @MaDoan = Doan
		DECLARE @DonGia INT
		SELECT @DonGia = GiaPhong FROM CHITIETPHONG WHERE @MaPhong = MaPhong
		
	



		--MA GIAO DICH LAY TU GIAO DICH CUA THANG TRUONG DOAN DA GIAO DICH TRUOC DO
		--CAN VIET FUNCTION TINH TONG TIEN DUA VAO NGAY BATDAU KET THUC VA DON GIA
		-- THE PHONG TU GENERA, GIO NHAP TRUOC NGAU NHIEN LA THE PHONG  'THE01'
 		INSERT INTO dbo.CHITIETGIAODICH VALUES (@MaGD,@MaDoan,@MaPhong,@MaKH,'2007-05-08','2007-05-09',@DonGia,1500000,'THE01')
		SET @KIEMTRA= 'THANH CONG, DA NHAP VAO CO SO DU LIEU'
		DECLARE @TinhTrang INT
		SET @TinhTrang = 1
		UPDATE CHITIETPHONG SET TinhTrang = 1 WHERE	@MaPhong = MaPhong
		PRINT ' '+@KIEMTRA 
	
	END
	ELSE
		PRINT ' DANG KY PHONG CHO BAN KHONG THANH CONG'
END
GO


-- Truoc khi thuc hien can insert Giao dich , Tai Khoan kich hoat cua doan
	EXEC NHAPGDTHANHVIENDOAN '001','Trinh Tan Tai','251136650','Forest',2,'2019-04-04 00:00:00.000'
	GO	

-- HUY DANG KY CUA THANH VIEN DOAN
-- Thanh vien thuc hien dang ky truoc do phai thong bao ho ten, CMND, MaDoan , Phong Da Dang Ky truoc do de Kiem Tra Thong Tin
--DROP PROCEDURE HUYDANGKY
GO
CREATE PROCEDURE HUYDANGKY
	@HoTen VARCHAR(45),
	@CMND VARCHAR(45),
	@MaDoan VARCHAR(4),
	@TenPhong VARCHAR(45)
AS
BEGIN
	DECLARE @KIEMTRA VARCHAR(45)
	DECLARE @MAGD VARCHAR(4)
	DECLARE @CHECK INT
	SELECT @KIEMTRA = TVD.HoTen FROM CHITIETGIAODICH CTGD,THANHVIENDOAN TVD,PHONG P WHERE @HoTen=TVD.HoTen AND @CMND=TVD.CMND AND TVD.MaKH = CTGD.MaKH AND @MaDoan = CTGD.MaDoan AND @TenPhong = P.TenPhong AND P.MaPhong = CTGD.MaPhong
	IF((@KIEMTRA IS NOT NULL) OR LEN(@KIEMTRA)>0)
	BEGIN
			SET @CHECK = 1
			SELECT @MAGD = CTGD.MaGD FROM CHITIETGIAODICH CTGD,THANHVIENDOAN TVD,PHONG P WHERE @HoTen=TVD.HoTen AND @CMND=TVD.CMND AND TVD.MaKH = CTGD.MaKH AND @MaDoan = CTGD.MaDoan AND @TenPhong = P.TenPhong AND P.MaPhong = CTGD.MaPhong
	END
		ELSE
			SET @CHECK = 0
	IF(@CHECK =1)
	BEGIN
		DELETE FROM CHITIETGIAODICH WHERE CHITIETGIAODICH.MaGD = @MAGD 
		DECLARE @MaPhong VARCHAR(3)
		SELECT @MaPhong = MaPhong FROM PHONG WHERE @TenPhong = TenPhong
		--CAP NHAT LAI TINH TRANG PHONG LA TRONG
		 UPDATE CHITIETPHONG SET TinhTrang = 0 WHERE @MaPhong = MaPhong
	END
END
GO	 

EXEC HUYDANGKY 'Trinh Tan Tai','251136650','001','Forest'
GO
--KIEM TRA TAI KHOAN :  xem thu nguoi dung da nhap tai khoan va mat khau chinh xac khong

CREATE PROCEDURE KIEMTRATAIKHOAN
	@TenDangNhap VARCHAR(15), 
	@MatKhau VARCHAR(15)
AS
BEGIN
	DECLARE @KIEMTRA VARCHAR(15)
	DECLARE @CHECK INT
	SELECT @KIEMTRA  = TenDangNhap FROM TAIKHOAN WHERE @TenDangNhap = TenDangNhap AND @MatKhau = MatKhau AND IsActive = 1 
	IF((@KIEMTRA IS NOT NULL) OR LEN(@KIEMTRA)>0)
	BEGIN
			SET @CHECK = 1
	END
		ELSE
			SET @CHECK = 0
	IF(@CHECK =1)
		PRINT 'DANG NHAP THANH CONG'
	ELSE
		PRINT 'DANG NHAP THAT BAI'
END
GO

EXEC KIEMTRATAIKHOAN  'admin01','1234'
GO

--DROP FUNCTION CONVERDATETOMINUTES
GO

--FUNCTION CHUYEN TU DATETIME SANG GIAY , TINH LUON KHOANG CACH GIUA 2 THOI GIAN CHUYEN SANG GIAY
CREATE FUNCTION CONVERDATETOMINUTES(@BatDau DATETIME , @KetThuc DATETIME)
RETURNS  INT
AS
BEGIN
DECLARE @TEMP1 INT
SET @TEMP1 = DATEDIFF(minute,@BatDau,@KetThuc)
RETURN @TEMP1
END
GO


DECLARE @TEMP2 INT
DECLARE @TEMP3 INT
SET @TEMP2 = dbo.CONVERDATETOMINUTES('2019-04-04 5:00:00','2019-04-04 9:00:00')
IF (@TEMP2 > 120)
	PRINT 'BAN DA HET THOI HAN DE NHAN PHONG'
ELSE
	PRINT 'NHAN PHONG THANH CONG'

-- NHAN PHONG, CHUC NANG NHAN PHONG PHAI THEO DOAN VA THONG QUA TUNG NGUOI TRONG DOAN
-- KHI DEN NHAN PHONG CAN NOI MA DOAN,  CMND ,PHONG MINH DA DAT TRUOC DO
GO

DROP PROCEDURE NHANPHONG
GO


CREATE PROCEDURE NHANPHONG
@MaDoan VARCHAR(4),
@CMND VARCHAR(45),
@TenPhong VARCHAR(45),
@BatDau DATETIME

AS
BEGIN
	DECLARE @KIEMTRA VARCHAR(50)
	DECLARE @CHECK INT
	DECLARE @CHECK2 INT
	SELECT @KIEMTRA = TVD.HoTen FROM THANHVIENDOAN TVD, CHITIETGIAODICH CTGD, PHONG P WHERE @CMND=TVD.CMND AND TVD.MaKH = CTGD.MaKH AND P.TenPhong =@TenPhong AND CTGD.MaPhong = P.MaPhong AND CTGD.BatDau = @BatDau
	DECLARE @MaGDD VARCHAR(4)
	
	IF((@KIEMTRA IS NOT NULL) OR LEN(@KIEMTRA)>0)
	BEGIN
			SET @CHECK2 = dbo.CONVERDATETOMINUTES(@BatDau,CURRENT_TIMESTAMP)
			IF(@CHECK2 < 120)
				SET @CHECK = 1
			ELSE
			BEGIN
				SET @CHECK = 0
				SELECT @MaGDD = CTGD.MaGD FROM THANHVIENDOAN TVD, CHITIETGIAODICH CTGD, PHONG P WHERE @CMND=TVD.CMND AND TVD.MaKH = CTGD.MaKH AND P.TenPhong =@TenPhong AND CTGD.MaPhong = P.MaPhong 
			END
	END
	ELSE
	BEGIN
		SET @CHECK = 0
		SELECT @MaGDD = CTGD.MaGD FROM THANHVIENDOAN TVD, CHITIETGIAODICH CTGD, PHONG P WHERE @CMND=TVD.CMND AND TVD.MaKH = CTGD.MaKH AND P.TenPhong =@TenPhong AND CTGD.MaPhong = P.MaPhong 
	END
	IF(@CHECK = 0)
	BEGIN
			
			DELETE FROM CHITIETGIAODICH WHERE CHITIETGIAODICH.MaGD = @MaGDD 
			DECLARE @MaPhong VARCHAR(3)
			SELECT @MaPhong = MaPhong FROM PHONG WHERE @TenPhong = TenPhong
			--CAP NHAT LAI TINH TRANG PHONG LA TRONG
			UPDATE CHITIETPHONG SET TinhTrang = 0 WHERE @MaPhong = MaPhong
			PRINT 'NHAN PHONG THAT BAI, MOI LAM LAI QUY TRINH'
	END
	ELSE
		PRINT 'NHAN PHONG THANH CONG'
END
GO

-- VIEC TOI NHAN PHONG CAN CHINH XAC, NEU NHAP SAI THONG TIN, QUY KHACH SE PHAI THUC HIEN GIAO DICH LAI TU DAU
EXEC NHANPHONG '001','251136650','Thunder','2019-11-26 21:45:00.000'



