CREATE DATABASE HOLYBIRD
GO

USE HOLYBIRD
GO

CREATE TABLE DOAN (
  MaDoan VARCHAR(4) NOT NULL,
  SoThanhVien INT NOT NULL,
  PRIMARY KEY (MaDoan)
)
CREATE TABLE  TAIKHOAN (
  MaDoan VARCHAR(4) NOT NULL,
  TenDangNhap VARCHAR(15) NOT NULL,
  MatKhau VARCHAR(15) NOT NULL,
  Doan_MaDoan VARCHAR(4) NOT NULL,
  IsActive BIT,
  PRIMARY KEY (MaDoan)  
)
	
	
CREATE TABLE GIAODICH(
  MaGD VARCHAR(4) NOT NULL,
  MaDoan VARCHAR(4) NOT NULL,
  SoPhong INT NOT NULL,
  BatDau DATETIME NOT NULL,
  KetThuc DATETIME NOT NULL,
  PRIMARY KEY (MaGD)
  )

CREATE TABLE THANHVIENDOAN (
  MaKH VARCHAR(4) NOT NULL,
  Doan VARCHAR(4) NOT NULL,
  HoTen VARCHAR(45) NOT NULL,
  CMND VARCHAR(45) NOT NULL,
  TruongDoan BIT NOT NULL,
  PRIMARY KEY (MaKH)
  
 )
 ALTER TABLE THANHVIENDOAN ADD CONSTRAINT fk_DOAN_THANHVIENDOAN FOREIGN KEY (Doan) 
 REFERENCES DOAN(MaDoan)

 ALTER TABLE GIAODICH ADD CONSTRAINT fk_GD_TK FOREIGN KEY (MaDoan)
 REFERENCES TAIKHOAN(MaDoan)

  ALTER TABLE TAIKHOAN ADD CONSTRAINT fk_TK_DOAN FOREIGN KEY (MaDoan)
 REFERENCES DOAN(MaDoan)


 CREATE TABLE THANHTOAN (
  MaGD VARCHAR(4) NOT NULL,
  MaDoan VARCHAR(4) NOT NULL,
  TongTien BIGINT NOT NULL,
  PRIMARY KEY (MaGD))

  CREATE TABLE CHITIETPHONG (
  MaPhong VARCHAR(3) NOT NULL,
  TinhTrang INT NOT NULL,
  Tang INT NOT NULL,
  GiaPhong INT NOT NULL,
  HinhThuc VARCHAR(45) NOT NULL,
  Hang VARCHAR(45) NOT NULL,
  PRIMARY KEY (MaPhong))

  ALTER TABLE THANHTOAN ADD CONSTRAINT FK_THANHTOAN_GIAODICH FOREIGN KEY(MaGD) REFERENCES dbo.GIAODICH(MaGD)

  CREATE TABLE CHITIETGIAODICH (
  MaGD VARCHAR(4) NOT NULL,
  MaDoan VARCHAR(4) NOT NULL,
  MaPhong VARCHAR(3) NOT NULL,
  MaKH VARCHAR(4) NOT NULL,
  BatDau DATETIME NOT NULL,
  KetThuc DATETIME NOT NULL,
  DonGia INT NOT NULL,
  ThanhTien INT NOT NULL,
  ThePhong VARCHAR(15) NOT NULL,
  PRIMARY KEY (MaGD))

  ALTER TABLE dbo.CHITIETGIAODICH ADD CONSTRAINT FK_CTGD_GD FOREIGN KEY(MaGD) REFERENCES dbo.GIAODICH(MaGD)

 CREATE TABLE PHONG (
  MaPhong VARCHAR(3) NOT NULL,
  TenPhong VARCHAR(45) NOT NULL,
  PRIMARY KEY (MaPhong)
  )

  CREATE TABLE BOITHUONG(
	MaGD VARCHAR(4) NOT NULL,
	Id INT IDENTITY(1,1) NOT NULL,
	MoTa NVARCHAR(200) NOT NULL,
	PhiBoiThuong INT NOT NULL
	PRIMARY KEY(MaGD,Id)
	)

  ALTER TABLE dbo.CHITIETGIAODICH ADD CONSTRAINT FK_CTGD_TVDOAN FOREIGN KEY(MaKH) REFERENCES dbo.THANHVIENDOAN(MaKH)

  ALTER TABLE dbo.CHITIETPHONG ADD CONSTRAINT FK_CTPHONG_PHONG FOREIGN KEY(MaPhong) REFERENCES dbo.PHONG(MaPhong)

  ALTER TABLE dbo.CHITIETGIAODICH ADD CONSTRAINT FK_CTGD_PHONG FOREIGN KEY(MaPhong) REFERENCES dbo.PHONG(MaPhong)

  ALTER TABLE dbo.BOITHUONG ADD	CONSTRAINT FK_BT_CTGD FOREIGN KEY(MaGD) REFERENCES dbo.CHITIETGIAODICH(MaGD)