CREATE DATABASE HOLYBIRD_DA2

USE HOLYBIRD_DA2

CREATE TABLE DOAN (
  MaDoan VARCHAR(4) NOT NULL,
  SoThanhVien INT NOT NULL,
  PRIMARY KEY (MaDoan)
)
CREATE TABLE  TAIKHOAN (
  MaDoan VARCHAR(4) NOT NULL,
  TenDangNhap VARCHAR(15) NOT NULL,
  MatKhau VARCHAR(15) NOT NULL,
  Doan_MaDoan VARCHAR(4) NOT NULL,
  IsActive BIT,
  PRIMARY KEY (MaDoan)  
  
)
	
	
CREATE TABLE GIAODICH(
  MaGD VARCHAR(4) NOT NULL,
  MaDoan VARCHAR(4) NOT NULL,
  SoPhong INT NOT NULL,
  BatDau DATETIME NOT NULL,
  KetThuc DATETIME NOT NULL,
  PRIMARY KEY (MaGD, MaDoan)
  )

CREATE TABLE THANHVIENDOAN (
  MaKH VARCHAR(4) NOT NULL,
  Doan VARCHAR(4) NOT NULL,
  HoTen VARCHAR(45) NOT NULL,
  CMND VARCHAR(45) NOT NULL,
  TruongDoan BIT NOT NULL,
  PRIMARY KEY (Doan, MaKH)
  
 )
 ALTER TABLE THANHVIENDOAN ADD CONSTRAINT fk_DOAN_THANHVIENDOAN FOREIGN KEY (Doan) 
 REFERENCES DOAN(MaDoan)

 ALTER TABLE GIAODICH ADD CONSTRAINT fk_GD_TK FOREIGN KEY (MaDoan)
 REFERENCES TAIKHOAN(MaDoan)

  ALTER TABLE TAIKHOAN ADD CONSTRAINT fk_TK_DOAN FOREIGN KEY (MaDoan)
 REFERENCES DOAN(MaDoan)


 INSERT INTO DOAN VALUES ('001',3)